title: Summer Scholars Presentation Summer 2019
description: 'Ante Post Bellum Seeking Records Conventions'
theme: jekyll-theme-Dinky

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: post
