title: Summer Scholars Presentation Summer 2019
description: 'Post Bellum Seeking Records Conventions'
theme: jekyll-theme-Modernist

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: post
